### ISSUE TITLE
Catch error

### ISSUE THREAD

**Issue by ochorocho** [perry-mitchell/webdav-fs#69]
Hey, 

when i try to create a already existing folder using `await client.createDirectory(target);` i get an error (see below) 

Is there any option to suppress such messages? 
An alternative would be to check if the file exists if this is possible? 

```
Error: Request failed with status code 405
    at createError (/Users/jochen/php-projekt-data/kap-nextcloud/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/jochen/php-projekt-data/kap-nextcloud/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/jochen/php-projekt-data/kap-nextcloud/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Thanks :-)

EDIT: This happens only if that folder already exists.

**Comment by perry-mitchell** [comment]
Hi! I think you posted on the wrong repo. There's no `createDirectory` in this repo - that's in [webdav-client](https://github.com/perry-mitchell/webdav-client)
