### ISSUE TITLE
TypeError: he.decode is not a function

### ISSUE THREAD

**Issue by sytolk** [perry-mitchell/webdav-fs#83]
I have this error on 
```javascript
wfs.stat(path, (err, stats) => {
        if (err) {
          return;
        }
})
```

```
TypeError: he.decode is not a function
    at Object.decodeHTMLEntities (/Users/sytolk/IdeaProjects/tagspaces-common/common-webdav/node_modules/webdav/dist/node/tools/encode.js:9:19)
    at prepareFileFromProps (/Users/sytolk/IdeaProjects/tagspaces-common/common-webdav/node_modules/webdav/dist/node/tools/dav.js:77:29)
    at Object.parseStat (/Users/sytolk/IdeaProjects/tagspaces-common/common-webdav/node_modules/webdav/dist/node/tools/dav.js:117:12)
    at Object.<anonymous> (/Users/sytolk/IdeaProjects/tagspaces-common/common-webdav/node_modules/webdav/dist/node/operations/stat.js:69:34)
    at step (/Users/sytolk/IdeaProjects/tagspaces-common/common-webdav/node_modules/webdav/dist/node/operations/stat.js:33:23)
    at Object.next (/Users/sytolk/IdeaProjects/tagspaces-common/common-webdav/node_modules/webdav/dist/node/operations/stat.js:14:53)
    at fulfilled (/Users/sytolk/IdeaProjects/tagspaces-common/common-webdav/node_modules/webdav/dist/node/operations/stat.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
![C047FC4B-563D-4E15-8B05-2C28911AE0DD](https://user-images.githubusercontent.com/1415463/144079345-303e3341-414e-4aa6-884f-2bea3fc3f8c4.png)

**Comment by perry-mitchell** [comment]
Can you provide the file or a simple example project? I’d need this to reproduce.

**Comment by sytolk** [comment]
just run this test: https://github.com/tagspaces/tagspaces-common/blob/TSN26x---WebDav-re-integration/package.json#L11
