### ISSUE TITLE
wfs.rename Headers Destination forbidden

### ISSUE THREAD

**Issue by sytolk** [perry-mitchell/webdav-fs#85]
after rename
```javascript
wfs.rename("/sample.bmp", "/sample1.bmp", err => {
    // handle error
});
```
this is the error:
```
{
  "message": "Network Error",
  "name": "AxiosError",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Authorization": "Basic d2ViZGF2OjEyMzQ=",
      "Destination": "http://localhost:8000/sample1.bmp"
    },
    "url": "http://localhost:8000/sample.bmp",
    "method": "move"
  },
  "code": "ERR_NETWORK",
  "status": null
}
```

 ```
console.error
      Error: Headers Destination forbidden
          at dispatchError (/Users/sytolk/IdeaProjects/tagspaces-common/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
          at validCORSPreflightHeaders (/Users/sytolk/IdeaProjects/tagspaces-common/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:102:5)
          at Request.<anonymous> (/Users/sytolk/IdeaProjects/tagspaces-common/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:374:12)
          at Request.emit (events.js:400:28)
          at Request._processResponse (/Users/sytolk/IdeaProjects/tagspaces-common/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:228:12)
          at ClientRequest.<anonymous> (/Users/sytolk/IdeaProjects/tagspaces-common/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:101:12)
          at Object.onceWrapper (events.js:520:26)
          at ClientRequest.emit (events.js:400:28)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
          at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17) undefined

```

**Comment by sytolk** [comment]
I have fix this after adding Destination header in Access-Control-Allow-Headers:
```
headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods":
        "HEAD, GET, PUT, PROPFIND, DELETE, OPTIONS, MKCOL, MOVE, COPY",
      "Access-Control-Allow-Headers":
        "Accept, Authorization, Content-Type, Content-Length, Depth, Destination",
    },
```
but it strange that in your tests works without this header: https://github.com/perry-mitchell/webdav-fs/blob/master/test/specs/index.js#L53

I have `jsdom` dependency in node_modules (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js)
![1233D818-29A2-41E7-9A55-5891AF50706E](https://user-images.githubusercontent.com/1415463/176732866-ff266bb1-34d5-4fb5-8443-a28feec6e2ea.png)
